name: Run ecephys_etl_pipeline tests
name: ci/github-actions
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: flake8 linting
        run: |
          pip install flake8
          export PATH="/home/runner/.local/bin:${PATH}"
          git fetch origin master
          # `|| true` to force exit code 0 even if no files found
          CHANGED_PYFILES=$(git diff --name-only --diff-filter AM origin/master ecephys_etl_pipelines | grep -e ".*.py$" || true)
          echo "List of changed files:"
          echo ${CHANGED_PYFILES}
          flake8 ${CHANGED_PYFILES} --count

  ecephys_etl_pipelines:
    name: ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "windows-latest", "ubuntu-latest"]
        python-version: ["3.6", "3.7"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test-env
      - name: Install
        run: |
          conda activate test-env
          pip install codecov
          pip install -r test_requirements.txt
          pip install .
      - name: Test
        run: |
          py.test --cov=ecephys_etl_pipelines -n 4
